title: "@KUNKA YUNSANG Tech BLOG."
author: YUNSANG
subtitle: The life of a frustrated engineer

url: "https://JeongYS.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/JeongYS"
footer_text: "Theme by JeongYS"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://www.notion.so/9206f8d6feb5462dae2e721954c5e4ed"
